In [1]:
from allennlp.modules.matrix_attention.linear_matrix_attention import LinearMatrixAttention
from allennlp.nn import util

import torch as th

In [2]:
self_attention = LinearMatrixAttention(800, 800, 'x,y,x*y')

In [20]:
x = th.rand(1,1,800)
y = th.rand(1,69,800)
self_attention(x,y).size()

torch.Size([1, 1, 69])

In [10]:
predictions = th.randn(3,5)

In [669]:
predictions

tensor([[ 1.2188, -0.6998,  1.1127,  0.3072,  1.0043],
        [ 0.6953,  0.4697, -0.0422,  0.3413, -1.2633],
        [ 1.5753,  0.4542,  1.2470,  1.1029, -0.4689]])

In [680]:
gold_labels = th.tensor([[1,1,1,0,0],[0,0,0,1,0],[1,0,1,0,0]]).float()

In [681]:
predictions,gold_labels

(tensor([[ 1.2188, -0.6998,  1.1127,  0.3072,  1.0043],
         [ 0.6953,  0.4697, -0.0422,  0.3413, -1.2633],
         [ 1.5753,  0.4542,  1.2470,  1.1029, -0.4689]]),
 tensor([[ 1.,  1.,  1.,  0.,  0.],
         [ 0.,  0.,  0.,  1.,  0.],
         [ 1.,  0.,  1.,  0.,  0.]]))

In [713]:
k = 5
top_k = predictions.topk(k)[0][:,k-1]
top_k

tensor([-0.6998, -1.2633, -0.4689])

In [718]:
predictions = torch.ge(predictions,top_k.unsqueeze(1).expand(predictions.size(0),predictions.size(1))).float()

In [719]:
((((gold_labels + predictions) >= 2).sum(1).float()/gold_labels.sum(1).float()).sum()/3)

tensor(1.)

In [4]:
x = th.rand(26,800)

In [24]:
x.max(-1)[1].float().squeeze(-1)

tensor([ 756.,  764.,  265.,  260.,  380.,  516.,  389.,  331.,  366.,
         317.,  595.,  628.,  428.,  796.,    6.,  347.,  729.,  207.,
          61.,  255.,  614.,  244.,  109.,  711.,  317.,  320.])

In [71]:
true = th.tensor([[1,0,0],[1,0,1],[0,1,1],[0,1,0]]).float()
predict = th.tensor([[1,0,0],[0,0,1],[1,0,0],[0,0,1]]).float()

In [17]:
(true*predict)

tensor([[ 1.,  0.,  0.],
        [ 0.,  0.,  1.]])

In [18]:
(true*predict)[:,0]

tensor([ 1.,  0.])

In [35]:
true[:,0],predict[:,0]

(tensor([ 1.,  1.,  0.,  0.]), tensor([ 1.,  0.,  1.,  0.]))

In [36]:
t0 = true[:,0]
p0 = predict[:,0]

In [37]:
(t0*p0).sum()

tensor(1.)

In [59]:
((1-t0)*(1-p0))

tensor([ 0.,  0.,  0.,  1.])

In [43]:
(1-(t0*p0)).sum()

tensor(3.)

In [52]:
(p0-t0).sum()

tensor(0.)

In [57]:
((1-t0)*p0)

tensor([ 0.,  0.,  1.,  0.])

In [58]:
(t0*(1-p0))

tensor([ 0.,  1.,  0.,  0.])

In [75]:
true

tensor([[ 1.,  0.,  0.],
        [ 1.,  0.,  1.],
        [ 0.,  1.,  1.],
        [ 0.,  1.,  0.]])

In [76]:
predict

tensor([[ 1.,  0.,  0.],
        [ 0.,  0.,  1.],
        [ 1.,  0.,  0.],
        [ 0.,  0.,  1.]])

In [74]:
((true*predict).sum(1)/true.sum(1)).sum()

tensor(1.5000)

In [110]:
true

tensor([[ 1.,  0.,  0.],
        [ 1.,  0.,  1.],
        [ 0.,  1.,  1.],
        [ 0.,  1.,  0.]])

In [111]:
predict

tensor([[ 1.,  0.,  0.],
        [ 0.,  0.,  1.],
        [ 1.,  0.,  0.],
        [ 0.,  0.,  1.]])

In [122]:
true[:,l] * predict[:,l]

tensor([ 0.,  1.,  0.,  0.])

In [143]:
l=0
(true[:,l] * predict[:,l]).sum()

tensor(1.)

In [144]:
(true*predict).sum(0)[l]

tensor(1.)

In [149]:
l=2
((1-true[:,l]) * (1- predict[:,l])).sum()

tensor(1.)

In [150]:
((1-true)*(1-predict)).sum(0)[l]

tensor(1.)

In [151]:
_true_positives = (true*predict).sum(0)

In [167]:
_false_positives = (true*predict).sum(0)

In [171]:
tmp = _true_positives / (_false_positives + 1e-13)

In [173]:
f1 = 2. * ((tmp * tmp) / (tmp + tmp + 1e-13))

In [175]:
f1.mean()

tensor(4.6667)

In [165]:
true.size()

torch.Size([4, 3])

In [32]:
from allennlp.modules import FeedForward

In [136]:
linear = FeedForward(5,2,10,'linear')

In [173]:
params = []
for n, param in linear.named_parameters():
    if 'weight' in n:
        params.append(param)
target_param = params[-1]

In [174]:
target_param

Parameter containing:
tensor([[ 0.1179, -0.2996,  0.1698,  0.2341,  0.1861,  0.2195, -0.0739,  0.1006,
         -0.1433,  0.1459],
        [ 0.1558, -0.1414, -0.0286, -0.3127, -0.2545,  0.0639,  0.2007, -0.0902,
         -0.0379,  0.0910],
        [-0.1573,  0.2527,  0.0598, -0.0828, -0.2393, -0.2237,  0.1925, -0.0457,
         -0.2069, -0.2214],
        [ 0.1934,  0.2431,  0.1339,  0.0987, -0.2624,  0.3061, -0.0556, -0.2501,
          0.1696, -0.1801],
        [ 0.1682,  0.0968,  0.0831,  0.2584,  0.1386, -0.0639,  0.2007,  0.0686,
         -0.1568, -0.2099],
        [-0.0444,  0.0677,  0.1154,  0.1922,  0.3126, -0.2419, -0.1068,  0.2502,
          0.1152,  0.1067],
        [ 0.2451, -0.1460, -0.2428,  0.1853, -0.2830,  0.0117,  0.1820,  0.1565,
          0.2472,  0.3086],
        [ 0.2736, -0.2389,  0.2741,  0.1414,  0.0016,  0.3063, -0.2257,  0.2314,
          0.1119,  0.0261],
        [ 0.2017, -0.2562, -0.1686,  0.2812,  0.2450, -0.1068, -0.2439,  0.0668,
         -0.0094, -0.1221

In [175]:
target_param[[1,1,1,1,3,5]]

tensor([[ 0.1558, -0.1414, -0.0286, -0.3127, -0.2545,  0.0639,  0.2007, -0.0902,
         -0.0379,  0.0910],
        [ 0.1558, -0.1414, -0.0286, -0.3127, -0.2545,  0.0639,  0.2007, -0.0902,
         -0.0379,  0.0910],
        [ 0.1558, -0.1414, -0.0286, -0.3127, -0.2545,  0.0639,  0.2007, -0.0902,
         -0.0379,  0.0910],
        [ 0.1558, -0.1414, -0.0286, -0.3127, -0.2545,  0.0639,  0.2007, -0.0902,
         -0.0379,  0.0910],
        [ 0.1934,  0.2431,  0.1339,  0.0987, -0.2624,  0.3061, -0.0556, -0.2501,
          0.1696, -0.1801],
        [-0.0444,  0.0677,  0.1154,  0.1922,  0.3126, -0.2419, -0.1068,  0.2502,
          0.1152,  0.1067]], grad_fn=<TakeBackward>)

In [169]:
th.norm(target_param[[1,3,5]]-target_param[[5,7,1]],2,1).sum()

tensor(2.8165, grad_fn=<SumBackward0>)

In [171]:
sgd.step()

In [159]:
sgd = th.optim.SGD(linear.parameters(), lr=0.001)

In [135]:
target_param

Parameter containing:
tensor([[ 0.0126,  0.2827, -0.4353,  0.0226,  0.0056],
        [-0.0643,  0.3521, -0.2954, -0.3986, -0.0568],
        [-0.2083, -0.2609,  0.0186, -0.1921,  0.1349],
        [ 0.3564,  0.4360,  0.0539,  0.0931,  0.1806],
        [ 0.2896,  0.4071,  0.2728,  0.0194,  0.2296],
        [-0.1640,  0.2470,  0.3195, -0.4202, -0.0181],
        [ 0.0951, -0.3350, -0.3095,  0.1322, -0.1912],
        [ 0.2780,  0.0138, -0.1370,  0.4208, -0.0639],
        [ 0.1533, -0.3238, -0.2623,  0.3911, -0.1782],
        [ 0.4145, -0.2262,  0.3164, -0.2626,  0.0993]], requires_grad=True)

In [65]:
th.norm(params[0][1][0]-params[0][1][1])

tensor(0.4545, grad_fn=<NormBackward0>)

In [46]:
lstm = th.nn.LSTM(10,1,10)

In [49]:
[i for i in lstm.parameters()]

[Parameter containing:
 tensor([[ 0.1670,  0.2917,  0.2211,  0.0153,  0.4960, -0.2319,  0.2642, -0.9624,
           0.3835, -0.8068],
         [-0.7509, -0.2114, -0.7882, -0.5555,  0.8680, -0.0634,  0.4944,  0.8323,
           0.0534, -0.2827],
         [ 0.9128, -0.2959,  0.7704,  0.2507, -0.2608,  0.6896,  0.7365, -0.7078,
          -0.2602,  0.5349],
         [-0.9607,  0.5065,  0.4523, -0.2891, -0.9092,  0.7098,  0.9130, -0.1830,
           0.6092,  0.7942]], requires_grad=True), Parameter containing:
 tensor([[-0.5741],
         [ 0.1430],
         [ 0.6417],
         [ 0.7707]], requires_grad=True), Parameter containing:
 tensor([0.9047, 0.3792, 0.2942, 0.3699], requires_grad=True), Parameter containing:
 tensor([ 0.4149, -0.7786, -0.0173,  0.3669], requires_grad=True), Parameter containing:
 tensor([[-0.8633],
         [ 0.8483],
         [-0.2649],
         [ 0.4731]], requires_grad=True), Parameter containing:
 tensor([[-0.1533],
         [ 0.9004],
         [ 0.6605],
       

In [48]:
t = []
for l,n in enumerate(hl):
    y = th.zeros(n,5*len(hl))
    y[:,l*5:(l+1)*5] = 1
    t.append(y)

In [49]:
x[0:5,3:6]=1

In [52]:
th.cat(t)

tensor([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.]])

In [56]:
x = th.randn(3,4)

In [75]:
x.unsqueeze(1).expand(-1,5,-1)

tensor([[[ 1.2884, -0.6896,  1.4009, -0.0840],
         [ 1.2884, -0.6896,  1.4009, -0.0840],
         [ 1.2884, -0.6896,  1.4009, -0.0840],
         [ 1.2884, -0.6896,  1.4009, -0.0840],
         [ 1.2884, -0.6896,  1.4009, -0.0840]],

        [[ 0.5904,  0.6352, -1.7919, -0.9090],
         [ 0.5904,  0.6352, -1.7919, -0.9090],
         [ 0.5904,  0.6352, -1.7919, -0.9090],
         [ 0.5904,  0.6352, -1.7919, -0.9090],
         [ 0.5904,  0.6352, -1.7919, -0.9090]],

        [[-0.5692,  2.1354,  0.0221, -0.0875],
         [-0.5692,  2.1354,  0.0221, -0.0875],
         [-0.5692,  2.1354,  0.0221, -0.0875],
         [-0.5692,  2.1354,  0.0221, -0.0875],
         [-0.5692,  2.1354,  0.0221, -0.0875]]])

In [81]:
x.size()

torch.Size([3, 4])

In [192]:
import itertools
from collections import defaultdict
import json
import pickle
from tqdm import tqdm
from my_library.losses.hierarchical_graph import HierarchicalGraph

In [193]:
with open('./data/lcsh/sh_path.json','r') as d:
    subject_paths = {}
    lines = d.readlines()
    for l in lines:
        subject_paths.update(json.loads(l.strip()))

In [194]:
with open('./data/lcsh/sh_hierarchy.json', "r") as hierarchy_file:
    etd_hierarchy = json.load(hierarchy_file)

In [195]:
with open('./data/all_etd_title_abstract_train_new.json', "r") as data_file:
    etd_jsons = []
    for line in data_file:
        line = line.strip("\n")
        if not line:
            continue
        etd_json = json.loads(line)
        abstract = etd_json['etdAbstract']
        labels = etd_json['lcsh']

        etd_jsons.append((abstract,labels))

In [196]:
lcsh = set(itertools.chain(*[l.keys() for _,l in etd_jsons]))
len(lcsh)

47446

In [197]:
groupby_level = {}
for l,sh in etd_hierarchy.items():
    intersect = list(lcsh.intersection(sh))
    if intersect:
        groupby_level[int(l)-1] = intersect

In [198]:
covered = list(itertools.chain(*[j for _,j in groupby_level.items()]))

In [199]:
uncovered = (lcsh.difference(covered))

In [200]:
len(covered)

47446

In [201]:
class_index = {}
idx = 0
for l,sh in groupby_level.items():
    for i in sh:
        class_index[i] = idx
        idx += 1

In [202]:
with open('../class_index.json','w') as f:
    json.dump(class_index, f)

In [230]:
with open('./data/index/all_etd_title_abstract_class_index.json','r') as f:
    class_to_idx = json.load(f)

In [231]:
i2c = {i:c for c,i in c.items()}

In [232]:
subject_paths['Machine learning']

['Science', 'Cognitive science', 'Artificial intelligence', 'Machine learning']

In [233]:
labels = list(etd_jsons[5][1].keys())

In [234]:
paths = [subject_paths[l] for l in labels]

In [235]:
set(itertools.chain(*paths))

{'Ability',
 'Art',
 'Arts',
 'Criminals',
 'Culture',
 'Human face recognition (Computer science)',
 'Humanities',
 'Identification photographs',
 'Intellectual life',
 'Learning ability',
 'Learning and scholarship',
 'Optical pattern recognition',
 'Perceptrons',
 'Persons',
 'Photographs',
 'Pictures',
 'Self-organizing systems'}

In [236]:
for _,ls in etd_jsons:
    labels = list(ls.keys())
    paths = [subject_paths[l] for l in labels]
    assert [class_to_idx[l] for l in set(itertools.chain(*paths))]

In [213]:
all_labels = [list(l.keys()) for _,l in etd_jsons]
all_labels = set(itertools.chain(*all_labels))
all_labels = set(itertools.chain(*[subject_paths[l] for l in all_labels]))

In [211]:
subject_paths['Hand-to-hand fighting, Oriental']

['Hand-to-hand fighting, Oriental']

In [212]:
for r in mads_subjects_graph._roots:
    subject_paths.update({r:[r]})

In [214]:
len(all_labels)

53879

In [215]:
groupby_level = {}
for l,sh in etd_hierarchy.items():
    intersect = list(all_labels.intersection(sh))
    if intersect:
        groupby_level[int(l)-1] = intersect

In [216]:
class_to_idx = {}
idx = 0
for l,sh in groupby_level.items():
    for i in sh:
        class_to_idx[i] = idx
        idx += 1

In [217]:
for _,ls in etd_jsons:
    labels = list(ls.keys())
    paths = [subject_paths[l] for l in labels]
    assert [class_to_idx[l] for l in set(itertools.chain(*paths))]

In [219]:
len(list(itertools.chain(*[j for _,j in groupby_level.items()])))

53879

In [238]:
class_to_idx['Hand-to-hand fighting, Oriental']

10255

In [241]:
with open('../test.json','w') as f:
    json.dump(groupby_level, f)

In [242]:
with open('../test.json','r') as f:
    test = json.load(f)

In [248]:
[len(l) for _,l in test.items()]

[11102, 10222, 8014, 8058, 6240, 4298, 2539, 1479, 972, 572, 245, 129, 9]

In [39]:
file_path = '../Data/lcsh/parsed/authoritiessubjects.dict'
with open(file_path,'rb') as d:
    mads_subjects = pickle.load(d)

In [40]:
missed = []
missed_lcsh = []
contained =[]
connections = []
for sb, details in tqdm(mads_subjects.items()):
    narrowers = details['narrowers']
    if narrowers:
        cnt = len(narrowers)
        for nar in narrowers:
            if nar not in mads_subjects:
                missed.append(nar)
                cnt -= 1
                continue
            connections.append((details['authoritativeLabel'],mads_subjects[nar]['authoritativeLabel']))
            contained.append(details['authoritativeLabel'])
            contained.append(mads_subjects[nar]['authoritativeLabel'])
        if cnt == 0:
            missed_lcsh.append(details['authoritativeLabel'])
    else:
        missed_lcsh.append(details['authoritativeLabel'])
root_n_leaf  = list(set(missed_lcsh).difference(contained))
connections = {'link': connections, 'root_n_leaf': root_n_leaf}

100%|██████████| 417721/417721 [00:01<00:00, 304994.56it/s]


In [41]:
mads_subjects_graph = HierarchicalGraph(directed=True)

In [42]:
mads_subjects_graph.load(connections)

100%|██████████| 63027/63027 [00:00<00:00, 1056965.21it/s]


In [43]:
graph_nodes = list(mads_subjects_graph._nodes.keys())
len(graph_nodes)

233727

In [44]:
mads_subjects_authoritativeLabel = [details['authoritativeLabel'] for sb, details in tqdm(mads_subjects.items())]
len(mads_subjects_authoritativeLabel)

100%|██████████| 417721/417721 [00:00<00:00, 1859521.78it/s]


417721

In [257]:
len(uncovered.intersection(graph_nodes))

0

In [46]:
len(uncovered.difference(mads_subjects_authoritativeLabel))

0

In [47]:
len(uncovered.difference(missed_lcsh))

64

In [48]:
len(uncovered.difference(contained))

0

In [50]:
len(uncovered.difference(root_n_leaf))

64

In [19]:
'Cold war' in mads_subjects_authoritativeLabel

False

In [20]:
'Cold War' in mads_subjects_authoritativeLabel

True

In [21]:
set([i.lower() for i in uncovered]).difference([i.lower() for i in missed_lcsh+contained])

set()

In [22]:
len(set([i.lower() for i in uncovered]).difference([i.lower() for i in mads_subjects_authoritativeLabel]))

0

In [39]:
len(set(contained+missed_lcsh))

416469

In [40]:
len(set(mads_subjects_authoritativeLabel))

416469

In [41]:
len(set(mads_subjects_authoritativeLabel).difference(list(mads_subjects_graph._nodes.keys())+missed_lcsh))

0

In [42]:
set(mads_subjects_authoritativeLabel).difference(list(mads_subjects_graph._nodes.keys())+missed_lcsh)

set()

In [43]:
len(set(contained))

233727

In [44]:
len(set(missed_lcsh))

353776

In [45]:
len(set(contained+missed_lcsh).difference(mads_subjects_authoritativeLabel))

0

In [46]:
len(set(mads_subjects_authoritativeLabel).difference(contained+missed_lcsh))

0

In [47]:
len(mads_subjects_graph._nodes.keys())

233727

In [51]:
len(set(mads_subjects_graph._nodes.keys()).intersection(set(root_n_leaf)))

0

In [49]:
len(set(missed_lcsh).difference(mads_subjects_graph._nodes.keys()))

182742

In [129]:
MultiLabelField([label for label,value in labels.items() if value == 1],skip_indexing=True)

ConfigurationError: "In order to skip indexing, your labels must be integers. Found labels = ['Child development']"

In [277]:
encoded_sentences = torch.randn(10)

In [282]:
x = encoded_sentences.unsqueeze(1).expand(-1, 13, -1)

In [281]:
encoded_sentences = encoded_sentences.unsqueeze(0) if len(encoded_sentences.size()) < 2 else encoded_sentences

tensor([[ 0.8127, -1.5018,  0.1780, -0.6542,  1.0974,  1.0849,  0.2327,  1.0172,
          1.1240, -0.6912]])

In [328]:
x = torch.randn(2,13,10)
w = [torch.randn(i+1,10) for i in range(13)]
x

tensor([[[ 0.8533,  0.4190, -2.0767, -0.0345,  0.6630, -0.7116,  1.5221,
           0.7992, -1.0465, -0.3173],
         [-0.6149,  0.9646,  0.3574,  1.1369,  2.1833,  0.9439, -2.7625,
           1.0525, -0.0339, -1.8345],
         [ 0.8095, -0.5504, -0.2730, -0.9327,  0.8884, -1.0047,  0.0709,
          -1.1145, -0.6126, -1.0040],
         [-0.4275,  1.4740,  1.6313, -0.3532, -0.5005, -0.0942, -1.6845,
           0.5843, -0.1975,  0.4605],
         [ 0.5792, -1.4113, -0.3771, -0.4636, -0.2917, -1.4306,  0.9793,
          -0.7659, -0.8269, -0.3076],
         [ 0.8639, -1.4813, -1.0534, -0.0316, -0.4078, -1.0978,  0.1940,
          -0.1055, -0.2257,  0.8761],
         [-0.4007, -0.1054, -0.4576,  0.0587, -0.5834, -2.8705,  1.7095,
          -2.5253, -0.5600, -1.8780],
         [-0.0916,  0.4525, -0.4344,  0.7702, -0.3336,  0.0061,  0.4410,
           0.5020,  1.9787,  0.8349],
         [ 0.8058, -2.2734, -0.5170,  0.4205,  0.6850, -1.3153,  2.1278,
           0.0507, -0.5713, -0.4724],
 

In [337]:
torch.cat([torch.nn.functional.linear(x[:,i,:],w[i],None) for i in range(13)], dim=1) + torch.ones(91)

tensor([[ 0.6059, -6.7942,  0.8046,  3.8361,  3.9413,  4.3066,  2.4927,  3.5499,
          1.0587, -2.4760, -0.7733, -0.7845,  0.0579,  2.7780,  2.3800,  1.3649,
         -1.5505,  3.3124, -0.1399,  5.7586, -1.6194,  2.9416, -1.8218,  6.2885,
          0.7569, -2.7944,  5.4584, -9.3708,  3.1077,  5.0431,  0.0940, -4.0578,
         -0.8638,  4.5924, -0.4655, -1.6509, -1.4189, -0.0906, -0.7262,  5.1204,
          0.3162, -1.1249,  2.6144,  1.9246,  1.2589,  4.3415,  9.1092,  3.2742,
          4.7613,  3.6194,  0.9449,  0.4045,  4.8451, -2.9840, -2.1515,  2.1143,
         -2.6395, -0.2799,  0.3988, -1.3586,  2.8291,  0.3997,  2.3667,  5.7298,
         -4.0207,  2.0423,  2.1108, -3.7583, -3.3623, -3.4064,  5.1331, -0.3764,
         -3.4477,  6.2547, -1.7320,  2.1923, -5.0698,  0.6963,  2.2288,  3.2331,
         -1.6346,  3.9578,  1.2025, -1.2038, -0.2823, -0.4072,  2.7594, -0.1961,
         -2.2852,  2.0799,  3.4738],
        [-0.3312,  0.1029,  2.8425,  5.0372,  7.8872, -1.5711,  4.1248, 

In [352]:
x = torch.rand(3,5)
x

tensor([[0.7855, 0.4102, 0.1455, 0.6103, 0.5276],
        [0.1901, 0.0534, 0.2029, 0.7552, 0.1263],
        [0.0534, 0.8271, 0.0519, 0.6432, 0.1110]])

In [367]:
(x[:,[1,3,4,4,4,4,4,4]] - x[:,[3,3,3,3,3,3,3,3]]).pow(2).sum(1).mean()

tensor(1.5600)

In [369]:
set([(1,2),(1,2),(3,4)])

{(1, 2), (3, 4)}

In [373]:
[3,2,1][-4]

IndexError: list index out of range

In [378]:
child_parent_pairs = []
with open('./data/index/etd_debug_child_parents.csv','r') as f:
    for l in f.readlines():
        pair = l.strip().split(',')
        child_parent_pairs.append((int(pair[0]),int(pair[1])))

In [2]:
import torch

In [7]:
x = torch.randn(3,10)
x

tensor([[-0.9586,  0.7083,  1.1294,  0.8688, -0.9867,  0.2612,  0.3218,  1.2775,
          0.3404, -0.5256],
        [ 0.1447, -0.0454,  2.1842, -0.8901, -0.6541,  0.7833, -0.8478,  0.6289,
          1.2716,  1.1189],
        [ 0.9744,  0.6664,  0.4691,  0.6247, -1.2273, -1.2953,  0.1572,  0.2920,
          0.0888, -0.7402]])

In [8]:
y = (torch.rand(3,10) > 0.5).float()
y 

tensor([[0., 1., 1., 0., 1., 0., 1., 1., 0., 1.],
        [0., 1., 1., 0., 1., 1., 0., 0., 0., 0.],
        [0., 1., 0., 1., 1., 1., 0., 0., 0., 0.]])

In [385]:
x.topk(3)

(tensor([[ 1.7140,  1.5113,  1.2477],
         [ 0.9857,  0.5312,  0.2728],
         [ 1.6699,  1.1535, -0.0951]]), tensor([[0, 2, 4],
         [7, 6, 3],
         [1, 5, 3]]))

In [498]:
mask = torch.tensor([[1,1,0]])
mask

tensor([[1, 1, 0]])

In [460]:
torch.cat([x.unsqueeze(0),x.unsqueeze(0)],dim=0).size()

torch.Size([2, 3, 10])

In [472]:
from allennlp.modules.matrix_attention.linear_matrix_attention import LinearMatrixAttention
from allennlp.nn import util

In [448]:
attn = LinearMatrixAttention(10,10,'x,y,x*y,x/y')

In [461]:
attn(torch.cat([x.unsqueeze(0),x.unsqueeze(0)],dim=0),torch.cat([x.unsqueeze(0),x.unsqueeze(0)],dim=0)).size()

torch.Size([2, 3, 3])

In [3]:
x

NameError: name 'x' is not defined

In [462]:
from allennlp.modules.seq2seq_encoders.multi_head_self_attention import MultiHeadSelfAttention

In [486]:
mhattn = MultiHeadSelfAttention(1,10,10,10,1)
mhattn(x.unsqueeze(0)).size()

torch.Size([1, 3, 1])

In [499]:
w = util.masked_softmax(mhattn(x.unsqueeze(0)).transpose(1,2),mask)

In [500]:
w

tensor([[[0.5000, 0.5000, 0.0000]]], grad_fn=<DivBackward1>)

In [496]:
0.3338*1.7140+0.3338*-0.0093+0.3325*-0.6944

0.33814086

In [9]:
x

tensor([[-0.9586,  0.7083,  1.1294,  0.8688, -0.9867,  0.2612,  0.3218,  1.2775,
          0.3404, -0.5256],
        [ 0.1447, -0.0454,  2.1842, -0.8901, -0.6541,  0.7833, -0.8478,  0.6289,
          1.2716,  1.1189],
        [ 0.9744,  0.6664,  0.4691,  0.6247, -1.2273, -1.2953,  0.1572,  0.2920,
          0.0888, -0.7402]])

In [493]:
util.weighted_sum(x.unsqueeze(0), w)

tensor([[[ 0.3381,  0.5187, -0.3685, -0.6713,  0.0726,  0.2058, -0.0107,
           0.2366, -0.4881, -0.7352]]], grad_fn=<BmmBackward>)

In [1]:
from my_library.models.etd_attention import MultiHeadAttentionEncoder

/misc/projdata3/info_fil/finance/simon_test/allennlp_official/allennlp/allennlp/service/predictors/__init__.py:23: FutureWarning: allennlp.service.predictors.* has been depreciated. Please use allennlp.predictors.*
  "Please use allennlp.predictors.*", FutureWarning)
/misc/projdata3/info_fil/finance/simon_test/allennlp_official/allennlp/allennlp/service/predictors/predictor.py:6: FutureWarning: allennlp.service.predictors.* has been deprecated. Please use allennlp.predictors.*
  " Please use allennlp.predictors.*", FutureWarning)


In [3]:
attn = MultiHeadAttentionEncoder(10)

In [9]:
x = torch.randn(2,3,10)
x.size()

torch.Size([2, 3, 10])

In [8]:
mask = torch.tensor([[1,1,0],[0,1,1]])

In [12]:
attn(x,mask)

tensor([[-1.3324, -0.7735,  2.0834,  0.3789, -1.7387, -0.2029,  0.7632, -0.5713,
         -0.0396, -1.0012],
        [ 1.1416, -1.1636, -0.2683,  0.4592, -0.8949,  0.2587, -0.0739,  0.0943,
          0.4202,  0.0145]], grad_fn=<SqueezeBackward0>)

In [15]:
torch.cat([torch.ones(5),torch.ones(6)])

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## HAN Allennlp Testing

In [103]:
from typing import Iterator, List, Dict, Optional, Union
from typing import List, Dict, Iterable
import json
import logging
import torch
import torch.optim as optim
import numpy as np

import spacy

from allennlp.common import Params
from allennlp.common.checks import ConfigurationError
from overrides import overrides
from allennlp.data import Instance
from allennlp.data.fields import ListField, TextField, SequenceLabelField, MultiLabelField
from allennlp.data.dataset_readers import DatasetReader
from allennlp.common.file_utils import cached_path
from allennlp.data.token_indexers import TokenIndexer, SingleIdTokenIndexer
from allennlp.data.tokenizers import Token, Tokenizer, WordTokenizer
from allennlp.data.vocabulary import Vocabulary
from allennlp.models import Model
from allennlp.modules import FeedForward, Seq2VecEncoder, TextFieldEmbedder, Seq2SeqEncoder
from allennlp.modules.text_field_embedders import TextFieldEmbedder, BasicTextFieldEmbedder
from allennlp.modules.token_embedders import Embedding
from allennlp.modules.seq2seq_encoders import Seq2SeqEncoder, PytorchSeq2SeqWrapper
from allennlp.nn.util import get_text_field_mask, sequence_cross_entropy_with_logits
from allennlp.nn import InitializerApplicator, RegularizerApplicator, util
from allennlp.nn.activations import Activation
from allennlp.training.metrics import CategoricalAccuracy
from allennlp.data.iterators import BucketIterator
from allennlp.training.trainer import Trainer
from allennlp.predictors import SentenceTaggerPredictor

from my_library.metrics.roc_auc_score import RocAucScore
from my_library.metrics.hit_at_k import *
from my_library.metrics.macro_f1 import *
from my_library.metrics.precision_at_k import *
from my_library.models.etd_attention import AttentionEncoder, MultiHeadAttentionEncoder
from my_library.models.customized_allennlp.maxout import Maxout

logger = logging.getLogger(__name__)
torch.manual_seed(1)

global x,y

In [104]:
class EtdHANAbstractReader(DatasetReader):
    """
    Reads a CSV-lines file containing abstract only from ETD records
    """
    def __init__(self,
                 tokenizer: Tokenizer = None,
                 token_indexers: Dict[str, TokenIndexer] = None,
                 merge_title_abstract: bool = False,
                 lazy: bool = False,
                 start_tokens: List[str] = ["<start>"], 
                 end_tokens: List[str] = ["<end>"]) -> None:
        super().__init__(lazy)
        self._tokenizer = tokenizer or WordTokenizer(start_tokens=start_tokens,end_tokens=end_tokens)
        self._sentence_splitter = spacy.load('en_core_web_sm')
        self._token_indexers = token_indexers or {"tokens": SingleIdTokenIndexer()}
        self._merge_title_abstract = merge_title_abstract
        
    @overrides
    def _read(self, file_path: str) -> Iterable[Instance]:
        with open(cached_path(file_path), "r") as data_file:
#             logger.info("Reading instances from lines in file at: %s", file_path)
            for line in data_file:
                line = line.strip("\n")
                if not line:
                    continue
                etd_json = json.loads(line)
                labels = etd_json['lcsh']
                if self._merge_title_abstract and 'etdTitle' in  etd_json:
                    abstract = '%s @@@SEP@@@ %s'%(etd_json['etdTitle'],etd_json['etdAbstract'])
                else:
                    abstract = etd_json['etdAbstract']
                labels = etd_json['lcsh']

                yield self.text_to_instance(abstract, labels)

    @overrides
    def text_to_instance(self, abstract_text: str, labels: Dict[str, int] = None) -> Instance:  # type: ignore
        # pylint: disable=arguments-differ
        sentences = [i.string.strip() for i in self._sentence_splitter(abstract_text).sents]
        tokenized_abstract_text = [self._tokenizer.tokenize(i) for i in sentences]
        abstract_text_field = ListField([TextField(i, self._token_indexers) for i in tokenized_abstract_text])
        fields = {'abstract_text': abstract_text_field}
        
        if labels is not None:
            fields['label'] = MultiLabelField([label for label,value in labels.items() if value == 1])
                
        return Instance(fields)

In [145]:
class EtdHAN(Model):
    """
    vocab : ``Vocabulary``, required
        A Vocabulary, required in order to compute sizes for input/output projections.
    text_field_embedder : ``TextFieldEmbedder``, required
        Used to embed the ``tokens`` ``TextField`` we get as input to the model.
    abstract_encoder : ``Seq2VecEncoder``
        The encoder that we will use to convert the abstract to a vector.
    classifier_feedforward : ``FeedForward``
    initializer : ``InitializerApplicator``, optional (default=``InitializerApplicator()``)
        Used to initialize the model parameters.
    regularizer : ``RegularizerApplicator``, optional (default=``None``)
        If provided, will be used to calculate the regularization penalty during training.
    """
    def __init__(self, vocab: Vocabulary,
                 text_field_embedder: TextFieldEmbedder,
                 word_encoder: Seq2SeqEncoder,
                 sentence_encoder: Seq2SeqEncoder,
                 classifier_feedforward: Union[FeedForward, Maxout],
                 attended_text_dropout: float  = 0.0,
                 bce_pos_weight: int = 10,
                 use_positional_encoding: bool = False,
                 initializer: InitializerApplicator = InitializerApplicator(),
                 regularizer: Optional[RegularizerApplicator] = None) -> None:
        super(EtdHAN, self).__init__(vocab, regularizer)

        self.text_field_embedder = text_field_embedder
        self.num_classes = self.vocab.get_vocab_size("labels")
        self.word_encoder = word_encoder
        self.word_level_attention = FeedForward(word_encoder.get_output_dim(), 
                                                2, 
                                                [word_encoder.get_output_dim(), 1],
                                                [Activation.by_name("tanh")(), Activation.by_name("linear")()],
                                                [True, False])
        self.sentence_encoder = sentence_encoder
        self.sentence_level_attention = FeedForward(sentence_encoder.get_output_dim(), 
                                                    2, 
                                                    [sentence_encoder.get_output_dim(), 1],
                                                    [Activation.by_name("tanh")(), Activation.by_name("linear")()],
                                                    [True, False])
        self.classifier_feedforward = classifier_feedforward
        self.use_positional_encoding = use_positional_encoding

        self._dropout = torch.nn.Dropout(attended_text_dropout)
        
        if text_field_embedder.get_output_dim() != word_encoder.get_input_dim():
            raise ConfigurationError("The output dimension of the text_field_embedder must match the "
                                     "input dimension of the word_encoder. Found {} and {}, "
                                     "respectively.".format(text_field_embedder.get_output_dim(),
                                                            word_encoder.get_input_dim()))

        self.metrics = {
#             "roc_auc_score": RocAucScore()            
            "hit_5": HitAtK(5),
            "hit_10": HitAtK(10),
            "precision_5": PrecisionAtK(5),
            "precision_10": PrecisionAtK(10)
#             "hit_100": HitAtK(100),
#             "macro_measure": MacroF1Measure(top_k=5,num_label=self.num_classes)
        }
        
        self.loss = torch.nn.BCEWithLogitsLoss(pos_weight = torch.ones(self.num_classes)*bce_pos_weight)

        initializer(self)

    @overrides
    def forward(self,  # type: ignore
                abstract_text: Dict[str, torch.LongTensor],
                label: torch.LongTensor = None) -> Dict[str, torch.Tensor]:
        # pylint: disable=arguments-differ
        embedded_abstract_text = self.text_field_embedder(abstract_text, num_wrapping_dims=1)
        abstract_text_mask = util.get_text_field_mask(abstract_text, num_wrapping_dims=1)
        
#         print(embedded_abstract_text.size())
        num_instance, num_sentence, num_word, _ = embedded_abstract_text.size()
        embedded_abstract_text = embedded_abstract_text.view(num_instance*num_sentence, num_word, -1)
        abstract_text_mask = abstract_text_mask.view(num_instance*num_sentence, -1)

        if self.use_positional_encoding:
            embedded_abstract_text = util.add_positional_features(embedded_abstract_text)
        encoded_abstract_text = self.word_encoder(embedded_abstract_text, abstract_text_mask)
        
        word_attentive_weights = self.word_level_attention(encoded_abstract_text)
        word_attentive_weights = util.masked_softmax(word_attentive_weights.transpose(1,2), 
                                                     abstract_text_mask, dim=2).transpose(1,2)
        attended_sentences = util.weighted_sum(encoded_abstract_text,word_attentive_weights.squeeze())
        
        attended_sentences = attended_sentences.view(num_instance, num_sentence, -1)
        abstract_text_mask = abstract_text_mask.view(num_instance, num_sentence, -1).sum(2).ge(1).long()
        
        if self.use_positional_encoding:
            attended_sentences = util.add_positional_features(attended_sentences)
        attended_sentences = self.sentence_encoder(attended_sentences, abstract_text_mask)
        
        sentence_attentive_weights = self.sentence_level_attention(attended_sentences)
        sentence_attentive_weights = util.masked_softmax(sentence_attentive_weights.transpose(1,2), 
                                                         abstract_text_mask, dim=2).transpose(1,2)
        attended_abstract_text = util.weighted_sum(attended_sentences,sentence_attentive_weights.squeeze())
        attended_abstract_text = self._dropout(attended_abstract_text)
        
        outputs = self.classifier_feedforward(attended_abstract_text)
        logits = torch.sigmoid(outputs)
        logits = logits.unsqueeze(0) if len(logits.size()) < 2 else logits
        output_dict = {'logits': logits}

        if label is not None:
            outputs = outputs.unsqueeze(0) if len(outputs.size()) < 2 else outputs
            loss = self.loss(outputs, label.squeeze(-1))
            for metric in self.metrics.values():
                metric(logits, label.squeeze(-1))
            output_dict["loss"] = loss
            
        return output_dict

    @overrides
    def decode(self, output_dict: Dict[str, torch.Tensor]) -> Dict[str, torch.Tensor]:
        """
        Does a simple argmax over the class probabilities, converts indices to string labels, and
        adds a ``"label"`` key to the dictionary with the result.
        """
        # class_probabilities = output_dict['logits']
        # output_dict['class_probabilities'] = class_probabilities

        # predictions = class_probabilities.cpu().data.numpy()
        # labels = [list(self.vocab.get_index_to_token_vocabulary(namespace="labels").values()) for i in range(len(output_dict['logits']))]
        # output_dict['label'] = labels
        return output_dict

    @overrides
    def get_metrics(self, reset: bool = False) -> Dict[str, float]:
#         metric_dict = {metric_name: metric.get_metric(reset) for metric_name, metric in self.metrics.items()}
        metric_dict = {}
        metric_dict['hit_5'] = self.metrics['hit_5'].get_metric(reset)
        metric_dict['hit_10'] = self.metrics['hit_10'].get_metric(reset)
#         metric_dict['hit_100'] = self.metrics['hit_100'].get_metric(reset)
        metric_dict['precision_5'] = self.metrics['precision_5'].get_metric(reset)
        metric_dict['precision_10'] = self.metrics['precision_10'].get_metric(reset)
#         macro_measure = self.metrics['macro_measure'].get_metric(reset)
#         metric_dict['mac_prec'] = macro_measure[0]
#         metric_dict['mac_rec'] = macro_measure[1]
#         metric_dict['mac_f1'] = macro_measure[2]
        return metric_dict

    @classmethod
    def from_params(cls, vocab: Vocabulary, params: Params) -> 'EtdHAN':
        embedder_params = params.pop("text_field_embedder")
        text_field_embedder = TextFieldEmbedder.from_params(vocab=vocab, params=embedder_params)
        word_encoder = Seq2SeqEncoder.from_params(params.pop("word_encoder"))
        sentence_encoder = Seq2SeqEncoder.from_params(params.pop("sentence_encoder"))
        classifier_feedforward = params.pop("classifier_feedforward")
        if classifier_feedforward.pop('type') == 'feedforward':
            classifier_feedforward = FeedForward.from_params(classifier_feedforward)
        else:
            classifier_feedforward = Maxout.from_params(classifier_feedforward)
        use_positional_encoding = params.pop("use_positional_encoding", False)
        bce_pos_weight = params.pop_int("bce_pos_weight", 10)
        attended_text_dropout = params.pop_float("attended_text_dropout", 0.0)

        initializer = InitializerApplicator.from_params(params.pop('initializer', []))
        regularizer = RegularizerApplicator.from_params(params.pop('regularizer', []))

        return cls(vocab=vocab,
                   text_field_embedder=text_field_embedder,
                   word_encoder=word_encoder,
                   sentence_encoder=sentence_encoder,
                   classifier_feedforward=classifier_feedforward,
                   attended_text_dropout=attended_text_dropout,
                   bce_pos_weight=bce_pos_weight,
                   use_positional_encoding=use_positional_encoding,
                   initializer=initializer,
                   regularizer=regularizer)

In [146]:
reader = EtdHANAbstractReader()

In [147]:
train_dataset = reader.read(cached_path(
    "/misc/projdata3/info_fil/finance/simon_test/ETD_cataloguing/allennlp-test/data/etd_debug.json"))
validation_dataset = reader.read(cached_path(
    "/misc/projdata3/info_fil/finance/simon_test/ETD_cataloguing/allennlp-test/data/etd_debug.json"))
vocab = Vocabulary.from_instances(train_dataset + validation_dataset)


0it [00:00, ?it/s]
4it [00:00, 28.75it/s]
10it [00:00, 36.53it/s]
16it [00:00, 41.35it/s]
21it [00:00, 42.37it/s]
26it [00:00, 43.64it/s]
31it [00:00, 44.54it/s]
37it [00:00, 45.98it/s]
42it [00:00, 44.75it/s]
48it [00:01, 45.62it/s]
53it [00:01, 45.62it/s]
58it [00:01, 45.82it/s]
63it [00:01, 45.72it/s]
69it [00:01, 45.87it/s]
75it [00:01, 46.58it/s]
81it [00:01, 47.28it/s]
87it [00:01, 47.40it/s]
93it [00:01, 47.73it/s]
99it [00:02, 47.26it/s]
105it [00:02, 47.78it/s]
111it [00:02, 47.55it/s]
117it [00:02, 47.93it/s]
123it [00:02, 47.75it/s]
130it [00:02, 48.23it/s]
136it [00:02, 47.99it/s]
141it [00:02, 47.88it/s]
146it [00:03, 47.90it/s]
152it [00:03, 48.08it/s]
159it [00:03, 48.62it/s]
165it [00:03, 48.54it/s]
171it [00:03, 48.40it/s]
177it [00:03, 48.57it/s]
183it [00:03, 48.58it/s]
189it [00:03, 48.19it/s]
194it [00:04, 48.09it/s]
200it [00:04, 48.33it/s]
205it [00:04, 48.24it/s]
210it [00:04, 48.19it/s]
215it [00:04, 48.23it/s]
220it [00:04, 47.94it/s]
225it [00:04, 47.83it/s]

In [148]:
EMBEDDING_DIM = 6
HIDDEN_DIM = 6
token_embedding = Embedding(num_embeddings=vocab.get_vocab_size('tokens'),
                            embedding_dim=EMBEDDING_DIM)
word_embeddings = BasicTextFieldEmbedder({"tokens": token_embedding})

In [149]:
word_lstm = PytorchSeq2SeqWrapper(torch.nn.LSTM(EMBEDDING_DIM, HIDDEN_DIM, bidirectional=True, batch_first=True))
sentence_lstm = PytorchSeq2SeqWrapper(torch.nn.LSTM(12, HIDDEN_DIM, bidirectional=True, batch_first=True))
ff = FeedForward(12,1,1714,Activation.by_name("linear")())
model = EtdHAN(vocab,
               text_field_embedder=word_embeddings, 
               word_encoder=word_lstm,
               sentence_encoder=sentence_lstm,
#                attention_encoder=attention_encoder,
               classifier_feedforward=ff)
optimizer = optim.SGD(model.parameters(), lr=0.001)
# iterator = BucketIterator(batch_size=16, sorting_keys=[("abstract_text", "list_num_tokens"),("abstract_text", "num_fields")])
# iterator = BucketIterator(batch_size=16, sorting_keys=[("abstract_text", "num_fields")])
iterator = BucketIterator(batch_size=1, sorting_keys=[("abstract_text", "list_num_tokens")])
iterator.index_with(vocab)

12/31/2018 17:10:38 - INFO - allennlp.nn.initializers -   Initializing parameters
12/31/2018 17:10:38 - INFO - allennlp.nn.initializers -   Done initializing parameters; the following parameters are using their default initialization from their code
12/31/2018 17:10:38 - INFO - allennlp.nn.initializers -      classifier_feedforward._linear_layers.0.bias
12/31/2018 17:10:38 - INFO - allennlp.nn.initializers -      classifier_feedforward._linear_layers.0.weight
12/31/2018 17:10:38 - INFO - allennlp.nn.initializers -      sentence_encoder._module.bias_hh_l0
12/31/2018 17:10:38 - INFO - allennlp.nn.initializers -      sentence_encoder._module.bias_hh_l0_reverse
12/31/2018 17:10:38 - INFO - allennlp.nn.initializers -      sentence_encoder._module.bias_ih_l0
12/31/2018 17:10:38 - INFO - allennlp.nn.initializers -      sentence_encoder._module.bias_ih_l0_reverse
12/31/2018 17:10:38 - INFO - allennlp.nn.initializers -      sentence_encoder._module.weight_hh_l0
12/31/2018 17:10:38 - INFO - alle

In [150]:
trainer = Trainer(model=model,
                  optimizer=optimizer,
                  iterator=iterator,
                  train_dataset=train_dataset,
                  validation_dataset=validation_dataset,
                  patience=10,
                  num_epochs=1000)

In [ ]:
trainer.train()

In [ ]:
abstract_text = {"tokens": torch.tensor([[[1,2,3,4,0,0],[1,2,0,0,0,0]],[[0,0,0,0,0,0],[1,2,1,6,0,0]]]).long()}
x,mask = model.text_field_embedder(abstract_text), util.get_text_field_mask(abstract_text, num_wrapping_dims=1)

In [135]:
x[0][0]

tensor([[-3.9800e-03,  9.8423e-03,  2.6894e-03, -2.3688e-03,  5.3659e-03,
          9.5438e-04],
        [ 7.0658e-03, -7.5392e-03, -1.4105e-03, -1.7417e-03,  2.8041e-03,
         -7.7285e-05],
        [ 1.6912e-02,  6.0203e-03, -7.2046e-03, -1.1684e-02, -3.2427e-03,
         -8.3448e-03],
        [-6.1995e-03,  9.2633e-04,  1.1533e-02,  1.0515e-02, -1.8912e-02,
          1.1993e-02],
        [ 9.9684e-03, -8.5390e-03, -3.7505e-03,  9.0805e-03, -1.8213e-02,
          1.1602e-02],
        [ 9.9684e-03, -8.5390e-03, -3.7505e-03,  9.0805e-03, -1.8213e-02,
          1.1602e-02]], grad_fn=<SelectBackward>)

In [137]:
x[0][0]

tensor([[-3.9800e-03,  9.8423e-03,  2.6894e-03, -2.3688e-03,  5.3659e-03,
          9.5438e-04],
        [ 7.0658e-03, -7.5392e-03, -1.4105e-03, -1.7417e-03,  2.8041e-03,
         -7.7285e-05],
        [ 1.6912e-02,  6.0203e-03, -7.2046e-03, -1.1684e-02, -3.2427e-03,
         -8.3448e-03],
        [-6.1995e-03,  9.2633e-04,  1.1533e-02,  1.0515e-02, -1.8912e-02,
          1.1993e-02],
        [ 9.9684e-03, -8.5390e-03, -3.7505e-03,  9.0805e-03, -1.8213e-02,
          1.1602e-02],
        [ 9.9684e-03, -8.5390e-03, -3.7505e-03,  9.0805e-03, -1.8213e-02,
          1.1602e-02]], grad_fn=<SelectBackward>)

In [120]:
x.size()

torch.Size([2, 6, 6])

In [267]:
y.sum(2).ge(1).long().size()

torch.Size([16, 19])

In [237]:
y[19]

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [74]:
x.size()

torch.Size([2, 10])

In [163]:
reader._read(cached_path(
    "/misc/projdata3/info_fil/finance/simon_test/ETD_cataloguing/allennlp-test/data/etd_debug.json"))

<generator object EtdAbstractReader._read at 0x7f9370bb8eb8>

In [83]:
iterator(reader._read(cached_path("/misc/projdata3/info_fil/finance/simon_test/ETD_cataloguing/allennlp-test/data/etd_debug.json")))

<generator object DataIterator.__call__ at 0x7f93719f1f10>

In [316]:
'@@@sent@@@'.join(['i am an apple','you are a boy']).split("@@@sent@@@")

['i am an apple', 'you are a boy']

In [325]:
x = torch.randn(3,10)
mask = torch.randn(3,10).ge(0.5).long()

In [320]:
mask

tensor([[0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0, 1, 0, 1, 0],
        [0, 0, 0, 0, 1, 1, 0, 0, 1, 0]], dtype=torch.uint8)

In [326]:
x*mask

RuntimeError: Expected object of type torch.FloatTensor but found type torch.LongTensor for argument #2 'other'

In [329]:
a,b= x.size()

In [417]:
input_dim = 10
hidden_dim = 5
num_hops = 3

x = torch.randn(5,6,input_dim)
mask = torch.randn(5,6).ge(0.3).long()

In [418]:
mask

tensor([[1, 0, 0, 0, 0, 1],
        [0, 1, 0, 1, 1, 1],
        [0, 1, 1, 1, 0, 1],
        [1, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]])

In [419]:
self_attention = torch.nn.Sequential(torch.nn.Linear(input_dim, hidden_dim, False), 
                                     torch.nn.Tanh(),
                                     torch.nn.Linear(hidden_dim, num_hops, False)
                                    )

In [420]:
A = self_attention(x)

In [423]:
A = util.masked_softmax(A.transpose(1,2), mask)

In [426]:
A.size()

torch.Size([5, 3, 6])

In [424]:
torch.bmm(A,x)[0]

tensor([[ 0.1309,  0.1582, -0.2105,  1.2122,  0.8495,  0.7268,  0.3333,  1.0941,
          1.3880, -0.2298],
        [-0.0723,  0.1661, -0.3527,  1.2330,  1.0729,  0.7947,  0.3510,  1.0121,
          1.5219, -0.1599],
        [ 0.0643,  0.1608, -0.2571,  1.2190,  0.9227,  0.7490,  0.3391,  1.0672,
          1.4319, -0.2069]], grad_fn=<SelectBackward>)

In [425]:
torch.bmm(A,x).view(-1, num_hops * input_dim)[0]

tensor([ 0.1309,  0.1582, -0.2105,  1.2122,  0.8495,  0.7268,  0.3333,  1.0941,
         1.3880, -0.2298, -0.0723,  0.1661, -0.3527,  1.2330,  1.0729,  0.7947,
         0.3510,  1.0121,  1.5219, -0.1599,  0.0643,  0.1608, -0.2571,  1.2190,
         0.9227,  0.7490,  0.3391,  1.0672,  1.4319, -0.2069],
       grad_fn=<SelectBackward>)

In [445]:
torch.norm(torch.bmm(A, A.transpose(1,2).contiguous()) - torch.eye(3,3))

tensor(3.3969, grad_fn=<NormBackward0>)

In [453]:
torch.bmm(A, A.transpose(1,2).contiguous())[0] - torch.eye(3,3)

tensor(1.4291, grad_fn=<NormBackward0>)

In [456]:
sum(torch.norm(i).pow(2) for i in torch.bmm(A, A.transpose(1,2).contiguous()) - torch.eye(3,3))

tensor(11.5388, grad_fn=<ThAddBackward>)

In [458]:
dim = A.size(1)
sum(torch.norm(i).pow(2) for i in torch.bmm(A, A.transpose(1,2).contiguous()) - torch.eye(dim, dim))

tensor(11.5388, grad_fn=<ThAddBackward>)

In [614]:
x = torch.randint(0,10, (5,10)).long()
[batch_size, sent_len] = x.size()

In [615]:
x.size()

torch.Size([5, 10])

In [616]:
embedding = torch.nn.ModuleList(
            [torch.nn.Embedding(10, 5, padding_idx=0) for _ in range(2 * 1 + 1)]
)

In [618]:
# padding_ = torch.LongTensor([0] * 1).expand(5,1)
# x_pad = torch.cat((padding_, x, padding_), dim=1)
x_pad = torch.nn.functional.pad(x, pad=(x.size(0),1))

In [622]:
x_pad

tensor([[0, 0, 0, 0, 0, 9, 4, 0, 2, 1, 3, 8, 2, 8, 0, 0],
        [0, 0, 0, 0, 0, 6, 5, 8, 5, 4, 0, 1, 2, 6, 9, 0],
        [0, 0, 0, 0, 0, 5, 7, 2, 6, 3, 4, 5, 7, 2, 7, 0],
        [0, 0, 0, 0, 0, 4, 8, 9, 8, 6, 8, 8, 4, 3, 8, 0],
        [0, 0, 0, 0, 0, 0, 8, 7, 2, 7, 0, 4, 5, 7, 2, 0]])

In [619]:
e = [embed(x_pad[:, i:(i + sent_len)]) for i, embed in enumerate(embedding)]
x_embed = torch.stack(e, dim=3)

In [620]:
multiple = torch.stack([x_embed[:, :, :, 1] * x_embed[:, :, :, i] for i in range(2 * 1 + 1)], dim=3)

local_context = torch.mean(multiple, dim=3)

In [621]:
local_context.size()

torch.Size([5, 10, 5])

In [611]:
x

tensor([[6, 2, 2, 8, 9, 5, 5, 9, 3, 1],
        [7, 5, 1, 1, 1, 1, 6, 8, 1, 3],
        [8, 4, 8, 5, 1, 5, 8, 9, 5, 3],
        [7, 6, 2, 6, 9, 5, 7, 3, 5, 1],
        [8, 3, 9, 1, 4, 6, 9, 8, 9, 4]])

In [637]:
from my_library.models.etd_attention import AttentionEncoder
from copy import deepcopy

In [632]:
att = AttentionEncoder(10)
x = torch.randn(2,5,10)
mask = torch.randn(2,5).ge(0.5).long()

In [638]:
att1 = deepcopy(att)

In [634]:
x,mask

(tensor([[[ 0.0956,  2.3094, -1.5023,  0.5245,  0.7895,  0.6708, -1.0538,
           -0.6314, -0.2453, -1.1940],
          [-1.7808,  0.4846, -0.9707, -0.4874,  1.9167,  0.4876, -0.9632,
           -0.5616,  3.5243,  1.5542],
          [ 1.2836,  0.1189,  0.6261, -0.2110, -1.4688,  1.2819,  0.5364,
            1.4083, -0.4425, -1.1375],
          [-1.1036, -0.4148, -0.1739,  0.0440, -2.1226, -1.9324,  0.9746,
           -1.8671, -0.0771, -0.9847],
          [-1.3612,  1.1472, -0.1760,  0.3716,  0.8115, -0.0025, -1.3948,
           -0.1042, -1.1905,  1.7788]],
 
         [[ 1.4873,  0.5854, -1.1582,  0.0561, -0.9787,  0.2971, -0.0266,
           -1.2644, -1.4301, -1.0191],
          [-0.9062, -1.6221,  0.4692, -1.4506,  0.3493,  0.1394, -0.6573,
            0.8878, -1.4329,  0.0296],
          [ 0.7715, -0.3434, -1.8192,  0.8519,  1.3127,  0.6217, -1.0981,
            0.4635, -1.2794, -1.5978],
          [-0.5934,  0.3613,  0.2303, -0.8669,  1.2360, -0.2357, -0.1621,
            0.6322,

In [639]:
att(x, mask),att1(x,mask)

(tensor([[-1.0969,  1.3949, -0.8407,  0.0925, -0.0282,  0.1934, -0.7274, -0.6720,
           0.6004,  0.0064],
         [-1.1849, -0.1936, -1.2598, -0.6128,  2.2592,  1.7331, -0.3720,  0.2144,
          -3.9588, -4.1431]], grad_fn=<SqueezeBackward0>),
 tensor([[-1.0969,  1.3949, -0.8407,  0.0925, -0.0282,  0.1934, -0.7274, -0.6720,
           0.6004,  0.0064],
         [-1.1849, -0.1936, -1.2598, -0.6128,  2.2592,  1.7331, -0.3720,  0.2144,
          -3.9588, -4.1431]], grad_fn=<SqueezeBackward0>))

In [649]:
loss=att1(x,mask).sum()
loss.backward()

In [660]:
atts = [att]
for i in range(10-1):
    atts.append(deepcopy(att))
atts = torch.nn.ModuleList(atts)

In [698]:
attended = torch.stack([i(x,mask) for i in atts], dim=1)

In [704]:
y = torch.randn(10)

In [705]:
torch.stack((y,y,y), dim=1).size()

torch.Size([10, 3])

In [711]:
y.unsqueeze(0).size()

torch.Size([1, 10])

In [699]:
attended[:, -1, :].size()

torch.Size([2, 10])

In [700]:
x.size(), attended.size()

(torch.Size([2, 5, 10]), torch.Size([2, 10, 10]))

In [650]:
for i in att1._self_attention.parameters():
    print(i.grad)

tensor([ 1.1495e-01,  3.3855e-01, -1.7647e-01,  3.7805e-02,  4.5963e-01,
         3.7307e-01, -2.9234e-01,  1.8206e-01,  9.5223e-02,  5.6805e-02,
        -2.1474e-07, -6.8533e-08, -4.1755e-08,  1.2824e-08, -3.1281e-07,
        -3.4604e-07,  1.4355e-07, -3.3732e-07, -6.9607e-09, -1.2825e-07])
tensor([1.4435e-07])


In [86]:
x = torch.randn(1,10,5)
x

tensor([[[ 0.0583, -0.5056,  0.7899, -0.8778,  0.9959],
         [ 0.0653,  1.0990,  0.5116,  0.2790, -0.0700],
         [-1.1550, -1.6063,  0.7777, -1.5428, -0.8389],
         [ 0.1843,  0.1167, -1.8287, -0.0539,  0.8898],
         [-0.8531,  1.3917,  2.3115,  0.4720,  0.8648],
         [-0.2575,  0.4673,  1.7664, -0.8929,  0.1301],
         [-0.2149, -0.8013,  1.4624,  0.8096,  1.1394],
         [-0.8729,  0.8131,  1.4391, -1.7514,  1.1175],
         [ 1.3564,  0.7563, -0.3517, -0.8089,  2.4565],
         [-0.1705,  0.4141, -0.6820,  1.4485, -1.1496]]])

In [102]:
x.sum(1).size()

torch.Size([1, 5])

In [1]:
from src.rule_predictor import RulePredictor
from collections import Counter

In [2]:
rule_predictor = RulePredictor()
rule_predictor.load('./data/lcsh/rules/variants_rules.txt')

100%|██████████| 1095464/1095464 [00:03<00:00, 301003.29it/s]


In [3]:
rule_predictor.predict_vote('machine learning')

'Knowledge and learning'

In [4]:
len(rule_predictor.predict('machine learning'))

416472

In [11]:
rule_predictor.predict_k(etd_json[0]['etdAbstract'])

{'Employees--Training of': 5,
 'Employee selection': 5,
 'Business enterprises': 5,
 'Employees': 4,
 'Personnel management': 3}

In [41]:
import torch

x = torch.randn(3,5,10)
c = torch.randn(3,10)
mask = torch.ones(3,5)
mask[1, 3:] = 0
mask[2, 1:] = 0

In [46]:
y = torch.randn(3,5)

In [45]:
x*c.transpose(1,0)

RuntimeError: The size of tensor a (10) must match the size of tensor b (3) at non-singleton dimension 2

In [34]:
x.bmm(mask.transpose(0,1))

RuntimeError: Expected 3-dimensional tensor, but got 2-dimensional tensor for argument #2 'batch2' (while checking arguments for bmm)

In [88]:
g = torch.randint(0,2,(5,5))
x = torch.randint(0,2,(3,5))
print(g,'\n',x)

tensor([[0, 1, 0, 0, 0],
        [0, 1, 1, 0, 1],
        [1, 0, 1, 1, 1],
        [1, 1, 0, 0, 0],
        [1, 1, 0, 1, 1]]) 
 tensor([[1, 1, 1, 1, 1],
        [1, 0, 0, 1, 0],
        [0, 0, 1, 0, 0]])


In [92]:
x.mm(g)

tensor([[3, 4, 2, 2, 3],
        [1, 2, 0, 0, 0],
        [1, 0, 1, 1, 1]])

In [145]:
x

tensor([[1, 1, 1, 1, 1],
        [1, 0, 0, 1, 0],
        [0, 0, 1, 0, 0]])

In [156]:
torch.eye(5,5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [157]:
0.2*(x.unsqueeze(-1).expand(3,5,5)*g).float()

tensor([[[0.0000, 0.2000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.2000, 0.2000, 0.0000, 0.2000],
         [0.2000, 0.0000, 0.2000, 0.2000, 0.2000],
         [0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
         [0.2000, 0.2000, 0.0000, 0.2000, 0.2000]],

        [[0.0000, 0.2000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],

        [[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.2000, 0.0000, 0.2000, 0.2000, 0.2000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]]])

In [162]:
(torch.eye(5,5) - 0.2*(x.unsqueeze(-1).expand(3,5,5)*g).float()).inverse()

tensor(23.1516)

In [216]:
ff = torch.nn.Linear(10,5)
opt = torch.optim.Adam(ff.parameters(), lr=0.01)

In [217]:
inputs = torch.randn(100,10)

In [219]:
for _ in range(100):
    o = torch.sigmoid(ff(inputs))
    o_size = o.size()
    o_inv = (torch.eye(o_size[-1],o_size[-1]) - 0.2*(o.unsqueeze(-1).expand(o_size[0],o_size[-1],o_size[-1])*g.float())).inverse()
    loss = o_inv.sum()
    
    opt.zero_grad()
    loss.backward()
    opt.step()
    
    print(loss)

tensor(690.3333, grad_fn=<SumBackward0>)
tensor(687.9799, grad_fn=<SumBackward0>)
tensor(685.6893, grad_fn=<SumBackward0>)
tensor(683.4610, grad_fn=<SumBackward0>)
tensor(681.2941, grad_fn=<SumBackward0>)
tensor(679.1877, grad_fn=<SumBackward0>)
tensor(677.1398, grad_fn=<SumBackward0>)
tensor(675.1490, grad_fn=<SumBackward0>)
tensor(673.2129, grad_fn=<SumBackward0>)
tensor(671.3298, grad_fn=<SumBackward0>)
tensor(669.4982, grad_fn=<SumBackward0>)
tensor(667.7164, grad_fn=<SumBackward0>)
tensor(665.9832, grad_fn=<SumBackward0>)
tensor(664.2968, grad_fn=<SumBackward0>)
tensor(662.6559, grad_fn=<SumBackward0>)
tensor(661.0593, grad_fn=<SumBackward0>)
tensor(659.5052, grad_fn=<SumBackward0>)
tensor(657.9922, grad_fn=<SumBackward0>)
tensor(656.5187, grad_fn=<SumBackward0>)
tensor(655.0835, grad_fn=<SumBackward0>)
tensor(653.6851, grad_fn=<SumBackward0>)
tensor(652.3223, grad_fn=<SumBackward0>)
tensor(650.9937, grad_fn=<SumBackward0>)
tensor(649.6979, grad_fn=<SumBackward0>)
tensor(648.4340,

tensor([[[1.0392, 0.2907, 0.0727, 0.0327, 0.0908],
         [0.1962, 1.4535, 0.3634, 0.1635, 0.4542],
         [0.4142, 0.2907, 1.3227, 0.3452, 0.4033],
         [0.2471, 0.3488, 0.0872, 1.0392, 0.1090],
         [0.3706, 0.5233, 0.1308, 0.3089, 1.4135]],

        [[1.0000, 0.2000, 0.0000, 0.0000, -0.0000],
         [0.0000, 1.0000, 0.0000, 0.0000, -0.0000],
         [0.0000, 0.0000, 1.0000, 0.0000, -0.0000],
         [0.2000, 0.2400, 0.0000, 1.0000, -0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 1.0000]],

        [[1.0000, 0.0000, 0.0000, 0.0000, -0.0000],
         [0.0000, 1.0000, 0.0000, 0.0000, -0.0000],
         [0.2500, 0.0000, 1.2500, 0.2500, 0.2500],
         [0.0000, 0.0000, 0.0000, 1.0000, -0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 1.0000]]])

In [1]:
from typing import List, Dict, Iterable
import json
import logging

from overrides import overrides

import tqdm

from allennlp.common import Params
from allennlp.common.checks import ConfigurationError
from allennlp.common.file_utils import cached_path
#from allennlp.data.dataset import Dataset
from allennlp.data.dataset_readers.dataset_reader import DatasetReader
from allennlp.data.fields import LabelField, TextField, MetadataField, ListField
from allennlp.data.fields.multilabel_field import MultiLabelField
from allennlp.data.instance import Instance
from allennlp.data.tokenizers import Token, Tokenizer, WordTokenizer
from allennlp.data.token_indexers import TokenIndexer, SingleIdTokenIndexer

logger = logging.getLogger(__name__)  # pylint: disable=invalid-name

# from multi_toxic_label.fields.multi_label_field import MultiLabelField

class EtdAbstractReader(DatasetReader):
    """
    Reads a CSV-lines file containing abstract only from ETD records
    """
    def __init__(self,
                 tokenizer: Tokenizer = None,
                 rules_dir: str,
                 token_indexers: Dict[str, TokenIndexer] = None,
                 merge_title_abstract: bool = False,
                 lazy: bool = False,
                 start_tokens: List[str] = ["<start>"], 
                 end_tokens: List[str] = ["<end>"]) -> None:
        super().__init__(lazy)
        self._tokenizer = tokenizer or WordTokenizer(start_tokens=start_tokens,end_tokens=end_tokens)
        self._token_indexers = token_indexers or {"tokens": SingleIdTokenIndexer()}
        self._merge_title_abstract = merge_title_abstract
        
        self._idx_to_rule = {}
        with open(rules_dir, 'r')  as f:
            for i,r in enumerate(f.readlines()):
                w,p = r.split(' => ')
                self._idx_to_rule[i] = (w.split(' ^ '), p)
        
    @overrides
    def _read(self, file_path: str) -> Iterable[Instance]:
        with open(cached_path(file_path), "r") as data_file:
            logger.info("Reading instances from lines in file at: %s", file_path)
            for line in data_file:
                line = line.strip("\n")
                if not line:
                    continue
                etd_json = json.loads(line)
                if self._merge_title_abstract and 'etdTitle' in  etd_json:
                    abstract = '%s @@@SEP@@@ %s'%(etd_json['etdTitle'],etd_json['etdAbstract'])
                else:
                    abstract = etd_json['etdAbstract']
                labels = etd_json['lcsh']

                yield self.text_to_instance(abstract, labels)

    @overrides
    def text_to_instance(self, abstract_text: str, labels: Dict[str, int] = None) -> Instance:  # type: ignore
        # pylint: disable=arguments-differ
        tokenized_abstract_text = self._tokenizer.tokenize(abstract_text)
        abstract_text_field = TextField(tokenized_abstract_text, self._token_indexers)
        fields = {'abstract_text': abstract_text_field}
        
        if labels is not None:
            fields['label'] = MultiLabelField([label for label,value in labels.items() if value == 1])
                
        return Instance(fields)

Deprecated cache directory found (/projdata3/info_fil/finance/simon_test/.allennlp/datasets).  Please remove this directory from your system to free up space.


In [2]:
from typing import List, Dict, Optional, Union

import numpy
from overrides import overrides
import torch
import torch.nn.functional as F

from allennlp.common import Params
from allennlp.common.checks import ConfigurationError
from allennlp.data import Vocabulary
from allennlp.modules import FeedForward, Seq2VecEncoder, TextFieldEmbedder, Seq2SeqEncoder
from allennlp.models.model import Model
from allennlp.nn import InitializerApplicator, RegularizerApplicator
from allennlp.nn import util
from allennlp.training.metrics import BooleanAccuracy

from my_library.metrics.roc_auc_score import RocAucScore
from my_library.metrics.hit_at_k import *
from my_library.metrics.macro_f1 import *
from my_library.metrics.precision_at_k import *
from my_library.models.etd_attention import AttentionEncoder, MultiHeadAttentionEncoder, SelfAttentionEncoder
from my_library.models.etd_pooling import Pooling
from my_library.models.customized_allennlp.maxout import Maxout

class EtdRNN(Model):
    def __init__(self, vocab: Vocabulary,
                 text_field_embedder: TextFieldEmbedder,
                 abstract_text_encoder: Seq2SeqEncoder,
                 attention_encoder: Union[AttentionEncoder, MultiHeadAttentionEncoder, SelfAttentionEncoder, Pooling],
                 classifier_feedforward: Union[FeedForward, Maxout],
                 bce_pos_weight: int = 10,
                 use_positional_encoding: bool = False,
                 initializer: InitializerApplicator = InitializerApplicator(),
                 regularizer: Optional[RegularizerApplicator] = None) -> None:
        super(EtdRNN, self).__init__(vocab, regularizer)

        self.text_field_embedder = text_field_embedder
        self.num_classes = self.vocab.get_vocab_size("labels")
        self.abstract_text_encoder = abstract_text_encoder
        self.attention_encoder = attention_encoder
        self.classifier_feedforward = classifier_feedforward
        self.use_positional_encoding = use_positional_encoding

        if text_field_embedder.get_output_dim() != abstract_text_encoder.get_input_dim():
            raise ConfigurationError("The output dimension of the text_field_embedder must match the "
                                     "input dimension of the abstract_text_encoder. Found {} and {}, "
                                     "respectively.".format(text_field_embedder.get_output_dim(),
                                                            abstract_text_encoder.get_input_dim()))

        self.metrics = {

        }
        
        self.loss = torch.nn.BCEWithLogitsLoss(pos_weight = torch.ones(self.num_classes)*bce_pos_weight)

        initializer(self)

    @overrides
    def forward(self,  # type: ignore
                abstract_text: Dict[str, torch.LongTensor],
                label: torch.LongTensor = None) -> Dict[str, torch.Tensor]:
        # pylint: disable=arguments-differ
        embedded_abstract_text = self.text_field_embedder(abstract_text)
        abstract_text_mask = util.get_text_field_mask(abstract_text)
        if self.use_positional_encoding:
            embedded_abstract_text = util.add_positional_features(embedded_abstract_text)
        encoded_abstract_text = self.abstract_text_encoder(embedded_abstract_text, abstract_text_mask)
        
        attended_abstract_text = self.attention_encoder(encoded_abstract_text, abstract_text_mask)
        outputs = self.classifier_feedforward(attended_abstract_text)
        logits = torch.sigmoid(outputs)
        logits = logits.unsqueeze(0) if logits.dim() < 2 else logits
        output_dict = {'logits': logits}

        if label is not None:
            outputs = outputs.unsqueeze(0) if outputs.dim() < 2 else outputs
            loss = self.loss(outputs, label.squeeze(-1))
            for metric in self.metrics.values():
                metric(logits, label.squeeze(-1))
            output_dict["loss"] = loss
            
        return output_dict

    @overrides
    def decode(self, output_dict: Dict[str, torch.Tensor]) -> Dict[str, torch.Tensor]:
        return output_dict

    @overrides
    def get_metrics(self, reset: bool = False) -> Dict[str, float]:
        metric_dict = {}
        return metric_dict

    @classmethod
    def from_params(cls, vocab: Vocabulary, params: Params) -> 'EtdRNN':
        embedder_params = params.pop("text_field_embedder")
        text_field_embedder = TextFieldEmbedder.from_params(vocab=vocab, params=embedder_params)
        abstract_text_encoder = Seq2SeqEncoder.from_params(params.pop("abstract_text_encoder"))
        attention_encoder = params.pop("attention_encoder")
        attention_type = attention_encoder.pop('type')
        if attention_type == 'linear_attention':
            attention_encoder = AttentionEncoder.from_params(attention_encoder)
        elif attention_type == 'self_attention':
            attention_encoder = SelfAttentionEncoder.from_params(attention_encoder)
        elif attention_type == 'multi_head':
            attention_encoder = MultiHeadAttentionEncoder.from_params(attention_encoder)
        else:
            attention_encoder = Pooling.from_params(attention_encoder)
        classifier_feedforward = params.pop("classifier_feedforward")
        if classifier_feedforward.pop('type') == 'feedforward':
            classifier_feedforward = FeedForward.from_params(classifier_feedforward)
        else:
            classifier_feedforward = Maxout.from_params(classifier_feedforward)
        use_positional_encoding = params.pop("use_positional_encoding", False)
        bce_pos_weight = params.pop_int("bce_pos_weight", 10)

        initializer = InitializerApplicator.from_params(params.pop('initializer', []))
        regularizer = RegularizerApplicator.from_params(params.pop('regularizer', []))

        return cls(vocab=vocab,
                   text_field_embedder=text_field_embedder,
                   abstract_text_encoder=abstract_text_encoder,
                   attention_encoder=attention_encoder,
                   classifier_feedforward=classifier_feedforward,
                   bce_pos_weight=bce_pos_weight,
                   use_positional_encoding=use_positional_encoding,
                   initializer=initializer,
                   regularizer=regularizer)

/misc/projdata3/info_fil/finance/simon_test/allennlp_official/allennlp/allennlp/service/predictors/__init__.py:23: FutureWarning: allennlp.service.predictors.* has been depreciated. Please use allennlp.predictors.*
  "Please use allennlp.predictors.*", FutureWarning)
/misc/projdata3/info_fil/finance/simon_test/allennlp_official/allennlp/allennlp/service/predictors/predictor.py:6: FutureWarning: allennlp.service.predictors.* has been deprecated. Please use allennlp.predictors.*
  " Please use allennlp.predictors.*", FutureWarning)


In [4]:
reader = EtdAbstractReader()
train_dataset = reader.read(cached_path(
    "/misc/projdata3/info_fil/finance/simon_test/ETD_cataloguing/allennlp-test/data/etd_debug.json"))
validation_dataset = reader.read(cached_path(
    "/misc/projdata3/info_fil/finance/simon_test/ETD_cataloguing/allennlp-test/data/etd_debug.json"))
vocab = Vocabulary.from_instances(train_dataset + validation_dataset)

0it [00:00, ?it/s]01/10/2019 17:20:26 - INFO - __main__ -   Reading instances from lines in file at: /misc/projdata3/info_fil/finance/simon_test/ETD_cataloguing/allennlp-test/data/etd_debug.json
955it [00:01, 688.49it/s]
0it [00:00, ?it/s]01/10/2019 17:20:27 - INFO - __main__ -   Reading instances from lines in file at: /misc/projdata3/info_fil/finance/simon_test/ETD_cataloguing/allennlp-test/data/etd_debug.json
955it [00:00, 1017.31it/s]
01/10/2019 17:20:28 - INFO - allennlp.data.vocabulary -   Fitting token dictionary from dataset.
100%|██████████| 1910/1910 [00:00<00:00, 4282.46it/s]
