In [117]:
import torch as th
import torch.nn.functional as F
from sklearn.metrics import roc_auc_score
from sklearn.metrics import hamming_loss
import numpy as np

In [17]:
true = th.tensor([[1,0,0],[0,0,0],[1,0,1]])
predicted = th.tensor([[0.3,0.6,0.2],[0.4,0.6,0.1],[0.8,0.3,0.5]])

In [18]:
true,predicted

(tensor([[ 1,  0,  0],
         [ 0,  0,  0],
         [ 1,  0,  1]]), tensor([[ 0.3000,  0.6000,  0.2000],
         [ 0.4000,  0.6000,  0.1000],
         [ 0.8000,  0.3000,  0.5000]]))

In [16]:
true.sum(0)

tensor([ 2,  1,  1])

In [21]:
one_label_columns = [i for i,x in enumerate(true.sum(0)) if x == 0]
one_label_columns

[1]

In [19]:
one_label_columns = [i for i,x in enumerate(true.sum(0)) if x == 0]
if one_label_columns != []:
    accuracy_one = 1 - predicted[:,one_label_columns].mean(0)
    accuracy_one = accuracy_one.mean()
    two_label_columns = [i for i,x in enumerate(true.sum(0)) if x != 0]
    if two_label_columns != []:
        gold_labels = true[:,two_label_columns]
        predictions = predicted[:,two_label_columns]
        try:
            accuracy_two = roc_auc_score(gold_labels,predictions)
        except ValueError as ve:
            print(ve)
            accuracy_two = 0
        accuracy = (accuracy_one + accuracy_two)/2
    else:
        accuracy = accuracy_one
else:
    accuracy = roc_auc_score(true,predicted)

In [30]:
[i for i,x in enumerate(true.sum(0)) if x != 0]

[0, 2]

In [31]:
        gold_labels = true[:,two_label_columns]
        predictions = predicted[:,two_label_columns]

In [33]:
accuracy_two = roc_auc_score(gold_labels,predictions)

In [38]:
predictions

tensor([[ 0.3000,  0.2000],
        [ 0.4000,  0.1000],
        [ 0.8000,  0.5000]])

In [37]:
gold_labels

tensor([[ 1,  0],
        [ 0,  0],
        [ 1,  1]])

In [116]:
roc_auc_score(np.array([[1,0],[0,1],[0,0],[1,1]]),np.array([[0.5,0.4],[0.5,0.4],[0.9,0.4],[1,0]]))

0.4375

In [112]:
roc_auc_score(np.array([[1,0],[0,1]]),np.array([[0.5,0.4],[0.5,0.4]]),average='micro')

0.5

In [113]:
roc_auc_score(np.array([[0,0],[1,1]]),np.array([[0.9,0.4],[1,0]]),average='micro')

0.5

In [88]:
roc_auc_score(np.array([1,0,0]),np.array([0.4,0.5,0]))

0.5

In [126]:
hamming_loss(np.array([[1,0],[0,1],[0,0],[1,1]]),np.array([[1,0],[1,0],[1,0],[1,0]]))

0.5

In [143]:
hamming_loss(true,predicted>0.2)

0.4444444444444444

In [150]:
loss = th.nn.BCELoss()

In [172]:
loss(predicted,th.tensor(true,dtype=th.float))

tensor(0.1464)

In [171]:
true = th.tensor([[1,0,0],[0,1,0],[1,0,1]])
predicted = th.tensor([[0.9,0.3,0.1],[0.1,0.9,0.1],[0.9,0.2,0.9]])

In [160]:
true

tensor([[ 1,  0,  0],
        [ 0,  1,  0],
        [ 1,  0,  1]])

In [165]:
predicted

tensor([[ 0.3000,  0.3000,  0.6000],
        [ 0.4000,  0.6000,  0.1000],
        [ 0.8000,  0.3000,  0.5000]])

In [29]:
(1 - predicted[:,one_label_columns].mean(0)).mean()

tensor(0.5000)

In [20]:
accuracy

tensor(0.6250)

In [180]:
output = th.tensor([[[1,0],[0,1],[1,0],[0,0],[1,1]],[[1,0],[0,1],[1,0],[0,0],[1,1]]],dtype=th.float)

In [183]:
output.mean(1).size()

torch.Size([2, 2])

In [181]:
output.size()

torch.Size([2, 5, 2])

In [284]:
x = th.tensor([[[1.,2.],[3.,4.]],[[1.,2.],[3.,4.]]])
y = th.tensor([[[1.,2.]],[[3.,4.]]])

In [270]:
x.unsqueeze(0).size()

torch.Size([1, 2, 2])

In [271]:
x.transpose(1,2)

RuntimeError: dimension out of range (expected to be in range of [-2, 1], but got 2)

In [288]:
x-y

tensor([[[ 0.,  0.],
         [ 2.,  2.]],

        [[-2., -2.],
         [ 0.,  0.]]])

In [292]:
y.size()

torch.Size([2, 1, 2])

In [297]:
th.cat((x,y),1).size()

torch.Size([2, 3, 2])

In [291]:
x.size()

torch.Size([2, 2, 2])

In [302]:
(x-y)

tensor([[[ 0.,  0.],
         [ 2.,  2.]],

        [[-2., -2.],
         [ 0.,  0.]]])

In [303]:
x

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 1.,  2.],
         [ 3.,  4.]]])

In [304]:
y

tensor([[[ 1.,  2.]],

        [[ 3.,  4.]]])

In [307]:
x.expand(-1,3)

RuntimeError: expand(torch.FloatTensor{[2, 2, 2]}, size=[-1, 3]): the number of sizes provided (2) must be greater or equal to the number of dimensions in the tensor (3)

In [309]:
z = th.tensor([[1.,2.],[3.,4.],[1.,2.],[3.,4.]])

In [317]:
z.size()

torch.Size([4, 2])

In [324]:
z.expand(-1,12)

RuntimeError: The expanded size of the tensor (12) must match the existing size (2) at non-singleton dimension 1

In [322]:
th.cat((z,z,z),dim=1).size()

torch.Size([4, 6])

In [329]:
z.repeat(1,3)

tensor([[ 1.,  2.,  1.,  2.,  1.,  2.],
        [ 3.,  4.,  3.,  4.,  3.,  4.],
        [ 1.,  2.,  1.,  2.,  1.,  2.],
        [ 3.,  4.,  3.,  4.,  3.,  4.]])

In [346]:
y[0]

tensor([[ 1.,  2.]])

In [384]:
y.unsqueeze(-1).size()

torch.Size([2, 1, 2, 1])

In [379]:
y.size()

torch.Size([2, 1, 2])

In [497]:
from allennlp.modules.matrix_attention.linear_matrix_attention import LinearMatrixAttention
from allennlp.nn import util

In [502]:
self_attention = LinearMatrixAttention(800, 800, 'x,y,x*y')

In [507]:
x = th.rand(1,26,800)
y = th.rand(1,40,800)
self_attention(x,y).size()

torch.Size([26, 26, 40])

In [504]:
self_attentive_weights_x = self_attention(x,y)

In [505]:
self_attentive_weights_x.size()

torch.Size([26, 26, 26])

In [487]:
th.bmm(self_attentive_weights_x.transpose(1,2), x).size()

torch.Size([1, 1, 800])

In [488]:
th.bmm(self_attentive_weights_x, y).size()

torch.Size([1, 26, 800])

In [445]:
self_attentive_weights_x.transpose(1,2).size()

torch.Size([1, 1, 26])

In [446]:
y.size()

torch.Size([1, 1, 800])

In [422]:
x.unsqueeze(2).size()

torch.Size([1, 26, 1, 800])

In [423]:
y.unsqueeze(1).size()

torch.Size([1, 1, 27, 800])

In [427]:
util.combine_tensors_and_multiply('x,y,x*y',[x.unsqueeze(2), y.unsqueeze(1)], th.ones(2400)).size()

torch.Size([26, 26, 27])

In [510]:
x.size(),y.size()

(torch.Size([1, 26, 800]), torch.Size([1, 40, 800]))

In [514]:
th.cat((x,x),dim=2).size()

torch.Size([1, 26, 1600])