In [3]:
import torch as th
import torch.nn.functional as F
from sklearn.metrics import roc_auc_score
from sklearn.metrics import hamming_loss
import numpy as np

In [17]:
true = th.tensor([[1,0,0],[0,0,0],[1,0,1]])
predicted = th.tensor([[0.3,0.6,0.2],[0.4,0.6,0.1],[0.8,0.3,0.5]])

In [18]:
true,predicted

(tensor([[ 1,  0,  0],
         [ 0,  0,  0],
         [ 1,  0,  1]]), tensor([[ 0.3000,  0.6000,  0.2000],
         [ 0.4000,  0.6000,  0.1000],
         [ 0.8000,  0.3000,  0.5000]]))

In [16]:
true.sum(0)

tensor([ 2,  1,  1])

In [21]:
one_label_columns = [i for i,x in enumerate(true.sum(0)) if x == 0]
one_label_columns

[1]

In [19]:
one_label_columns = [i for i,x in enumerate(true.sum(0)) if x == 0]
if one_label_columns != []:
    accuracy_one = 1 - predicted[:,one_label_columns].mean(0)
    accuracy_one = accuracy_one.mean()
    two_label_columns = [i for i,x in enumerate(true.sum(0)) if x != 0]
    if two_label_columns != []:
        gold_labels = true[:,two_label_columns]
        predictions = predicted[:,two_label_columns]
        try:
            accuracy_two = roc_auc_score(gold_labels,predictions)
        except ValueError as ve:
            print(ve)
            accuracy_two = 0
        accuracy = (accuracy_one + accuracy_two)/2
    else:
        accuracy = accuracy_one
else:
    accuracy = roc_auc_score(true,predicted)

In [30]:
[i for i,x in enumerate(true.sum(0)) if x != 0]

[0, 2]

In [31]:
        gold_labels = true[:,two_label_columns]
        predictions = predicted[:,two_label_columns]

In [33]:
accuracy_two = roc_auc_score(gold_labels,predictions)

In [38]:
predictions

tensor([[ 0.3000,  0.2000],
        [ 0.4000,  0.1000],
        [ 0.8000,  0.5000]])

In [37]:
gold_labels

tensor([[ 1,  0],
        [ 0,  0],
        [ 1,  1]])

In [116]:
roc_auc_score(np.array([[1,0],[0,1],[0,0],[1,1]]),np.array([[0.5,0.4],[0.5,0.4],[0.9,0.4],[1,0]]))

0.4375

In [112]:
roc_auc_score(np.array([[1,0],[0,1]]),np.array([[0.5,0.4],[0.5,0.4]]),average='micro')

0.5

In [113]:
roc_auc_score(np.array([[0,0],[1,1]]),np.array([[0.9,0.4],[1,0]]),average='micro')

0.5

In [88]:
roc_auc_score(np.array([1,0,0]),np.array([0.4,0.5,0]))

0.5

In [126]:
hamming_loss(np.array([[1,0],[0,1],[0,0],[1,1]]),np.array([[1,0],[1,0],[1,0],[1,0]]))

0.5

In [143]:
hamming_loss(true,predicted>0.2)

0.4444444444444444

In [150]:
loss = th.nn.BCELoss()

In [172]:
loss(predicted,th.tensor(true,dtype=th.float))

tensor(0.1464)

In [171]:
true = th.tensor([[1,0,0],[0,1,0],[1,0,1]])
predicted = th.tensor([[0.9,0.3,0.1],[0.1,0.9,0.1],[0.9,0.2,0.9]])

In [160]:
true

tensor([[ 1,  0,  0],
        [ 0,  1,  0],
        [ 1,  0,  1]])

In [165]:
predicted

tensor([[ 0.3000,  0.3000,  0.6000],
        [ 0.4000,  0.6000,  0.1000],
        [ 0.8000,  0.3000,  0.5000]])

In [29]:
(1 - predicted[:,one_label_columns].mean(0)).mean()

tensor(0.5000)

In [20]:
accuracy

tensor(0.6250)

In [180]:
output = th.tensor([[[1,0],[0,1],[1,0],[0,0],[1,1]],[[1,0],[0,1],[1,0],[0,0],[1,1]]],dtype=th.float)

In [183]:
output.mean(1).size()

torch.Size([2, 2])

In [181]:
output.size()

torch.Size([2, 5, 2])

In [284]:
x = th.tensor([[[1.,2.],[3.,4.]],[[1.,2.],[3.,4.]]])
y = th.tensor([[[1.,2.]],[[3.,4.]]])

In [270]:
x.unsqueeze(0).size()

torch.Size([1, 2, 2])

In [271]:
x.transpose(1,2)

RuntimeError: dimension out of range (expected to be in range of [-2, 1], but got 2)

In [288]:
x-y

tensor([[[ 0.,  0.],
         [ 2.,  2.]],

        [[-2., -2.],
         [ 0.,  0.]]])

In [292]:
y.size()

torch.Size([2, 1, 2])

In [297]:
th.cat((x,y),1).size()

torch.Size([2, 3, 2])

In [291]:
x.size()

torch.Size([2, 2, 2])

In [302]:
(x-y)

tensor([[[ 0.,  0.],
         [ 2.,  2.]],

        [[-2., -2.],
         [ 0.,  0.]]])

In [303]:
x

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 1.,  2.],
         [ 3.,  4.]]])

In [304]:
y

tensor([[[ 1.,  2.]],

        [[ 3.,  4.]]])

In [307]:
x.expand(-1,3)

RuntimeError: expand(torch.FloatTensor{[2, 2, 2]}, size=[-1, 3]): the number of sizes provided (2) must be greater or equal to the number of dimensions in the tensor (3)

In [309]:
z = th.tensor([[1.,2.],[3.,4.],[1.,2.],[3.,4.]])

In [317]:
z.size()

torch.Size([4, 2])

In [324]:
z.expand(-1,12)

RuntimeError: The expanded size of the tensor (12) must match the existing size (2) at non-singleton dimension 1

In [322]:
th.cat((z,z,z),dim=1).size()

torch.Size([4, 6])

In [329]:
z.repeat(1,3)

tensor([[ 1.,  2.,  1.,  2.,  1.,  2.],
        [ 3.,  4.,  3.,  4.,  3.,  4.],
        [ 1.,  2.,  1.,  2.,  1.,  2.],
        [ 3.,  4.,  3.,  4.,  3.,  4.]])

In [346]:
y[0]

tensor([[ 1.,  2.]])

In [384]:
y.unsqueeze(-1).size()

torch.Size([2, 1, 2, 1])

In [379]:
y.size()

torch.Size([2, 1, 2])

In [497]:
from allennlp.modules.matrix_attention.linear_matrix_attention import LinearMatrixAttention
from allennlp.nn import util

In [502]:
self_attention = LinearMatrixAttention(800, 800, 'x,y,x*y')

In [507]:
x = th.rand(1,26,800)
y = th.rand(1,40,800)
self_attention(x,y).size()

torch.Size([26, 26, 40])

In [668]:
predictions = th.randn(3,5)

In [669]:
predictions

tensor([[ 1.2188, -0.6998,  1.1127,  0.3072,  1.0043],
        [ 0.6953,  0.4697, -0.0422,  0.3413, -1.2633],
        [ 1.5753,  0.4542,  1.2470,  1.1029, -0.4689]])

In [680]:
gold_labels = th.tensor([[1,1,1,0,0],[0,0,0,1,0],[1,0,1,0,0]]).float()

In [681]:
predictions,gold_labels

(tensor([[ 1.2188, -0.6998,  1.1127,  0.3072,  1.0043],
         [ 0.6953,  0.4697, -0.0422,  0.3413, -1.2633],
         [ 1.5753,  0.4542,  1.2470,  1.1029, -0.4689]]),
 tensor([[ 1.,  1.,  1.,  0.,  0.],
         [ 0.,  0.,  0.,  1.,  0.],
         [ 1.,  0.,  1.,  0.,  0.]]))

In [713]:
k = 5
top_k = predictions.topk(k)[0][:,k-1]
top_k

tensor([-0.6998, -1.2633, -0.4689])

In [718]:
predictions = torch.ge(predictions,top_k.unsqueeze(1).expand(predictions.size(0),predictions.size(1))).float()

In [719]:
((((gold_labels + predictions) >= 2).sum(1).float()/gold_labels.sum(1).float()).sum()/3)

tensor(1.)

In [4]:
x = th.rand(26,800)

In [24]:
x.max(-1)[1].float().squeeze(-1)

tensor([ 756.,  764.,  265.,  260.,  380.,  516.,  389.,  331.,  366.,
         317.,  595.,  628.,  428.,  796.,    6.,  347.,  729.,  207.,
          61.,  255.,  614.,  244.,  109.,  711.,  317.,  320.])

In [71]:
true = th.tensor([[1,0,0],[1,0,1],[0,1,1],[0,1,0]]).float()
predict = th.tensor([[1,0,0],[0,0,1],[1,0,0],[0,0,1]]).float()

In [17]:
(true*predict)

tensor([[ 1.,  0.,  0.],
        [ 0.,  0.,  1.]])

In [18]:
(true*predict)[:,0]

tensor([ 1.,  0.])

In [35]:
true[:,0],predict[:,0]

(tensor([ 1.,  1.,  0.,  0.]), tensor([ 1.,  0.,  1.,  0.]))

In [36]:
t0 = true[:,0]
p0 = predict[:,0]

In [37]:
(t0*p0).sum()

tensor(1.)

In [59]:
((1-t0)*(1-p0))

tensor([ 0.,  0.,  0.,  1.])

In [43]:
(1-(t0*p0)).sum()

tensor(3.)

In [52]:
(p0-t0).sum()

tensor(0.)

In [57]:
((1-t0)*p0)

tensor([ 0.,  0.,  1.,  0.])

In [58]:
(t0*(1-p0))

tensor([ 0.,  1.,  0.,  0.])

In [75]:
true

tensor([[ 1.,  0.,  0.],
        [ 1.,  0.,  1.],
        [ 0.,  1.,  1.],
        [ 0.,  1.,  0.]])

In [76]:
predict

tensor([[ 1.,  0.,  0.],
        [ 0.,  0.,  1.],
        [ 1.,  0.,  0.],
        [ 0.,  0.,  1.]])

In [74]:
((true*predict).sum(1)/true.sum(1)).sum()

tensor(1.5000)

In [110]:
true

tensor([[ 1.,  0.,  0.],
        [ 1.,  0.,  1.],
        [ 0.,  1.,  1.],
        [ 0.,  1.,  0.]])

In [111]:
predict

tensor([[ 1.,  0.,  0.],
        [ 0.,  0.,  1.],
        [ 1.,  0.,  0.],
        [ 0.,  0.,  1.]])

In [122]:
true[:,l] * predict[:,l]

tensor([ 0.,  1.,  0.,  0.])

In [143]:
l=0
(true[:,l] * predict[:,l]).sum()

tensor(1.)

In [144]:
(true*predict).sum(0)[l]

tensor(1.)

In [149]:
l=2
((1-true[:,l]) * (1- predict[:,l])).sum()

tensor(1.)

In [150]:
((1-true)*(1-predict)).sum(0)[l]

tensor(1.)

In [151]:
_true_positives = (true*predict).sum(0)

In [167]:
_false_positives = (true*predict).sum(0)

In [171]:
tmp = _true_positives / (_false_positives + 1e-13)

In [173]:
f1 = 2. * ((tmp * tmp) / (tmp + tmp + 1e-13))

In [175]:
f1.mean()

tensor(4.6667)

In [165]:
true.size()

torch.Size([4, 3])